import namespace from '../namespace.js'
(function (global) {
	'use strict';

	const PLUGIN_TAG = '[AutoCopperPour]';
	const PCB_DOCUMENT_TYPE = 3;
	const SAFE_COPPER_WIDTH = 6;
	const POUR_LINE_WIDTH = 12;
	const MULTI_LAYER_ID = 12;
	const DEFAULT_PAD_BBOX_EXPANSION = 5;
	const DEFAULT_CHAMFER_WIDTH = 5;
	const CONFIG_KEY = 'autoCopperShape.panelConfig.v1';
	const SHOULD_USE_DYNAMIC_SHAPE = true;
	const OBSTACLE_SEARCH_MARGIN = 60;
	const EDGE_BLOCK_FORWARD_SEARCH_MARGIN = 40;
	const OBSTACLE_LATERAL_MARGIN = 16;
	const TRACE_CAP_SEGMENTS = 8;
	const COPPER_NODE_CONTOUR_SEGMENTS = 32;
	const ROUND_RECT_CORNER_SEGMENTS = 6;
	const MIN_TRACE_CLIPPED_POLYGON_AREA = SAFE_COPPER_WIDTH * SAFE_COPPER_WIDTH;
	const MIN_AVOIDANCE_NECK_WIDTH = SAFE_COPPER_WIDTH;
	const EDGE_BLOCK_FORWARD_GAP = Math.max(MIN_AVOIDANCE_NECK_WIDTH * 3, OBSTACLE_LATERAL_MARGIN);
	const EDGE_BLOCK_CORNER_DOMINANCE_RATIO = 1.25;
	const EDGE_BLOCK_CORNER_GAP_BIAS = 4;
	const TRACE_NECK_REPAIR_MAX_PASSES = 2;
	const TRACE_NECK_TRACE_EDGE_TOLERANCE = 2;
	const TRACE_NECK_REPAIR_INNER_OVERLAP = Math.max(2, POUR_LINE_WIDTH / 4);
	const MAX_DETOUR_LENGTH_RATIO = 1.65;
	const MAX_DETOUR_OFFSET_RATIO = 0.3;
	const MIN_DETOUR_CORNER_ANGLE = 35;
	const SHORT_BRIDGE_FALLBACK_GAP = Math.max(POUR_LINE_WIDTH * 3, MIN_AVOIDANCE_NECK_WIDTH * 6);
	const SHORT_BRIDGE_DETOUR_OFFSET_RATIO = 0.45;
	const SHORT_BRIDGE_SPIKE_CORNER_ANGLE = 50;
	const LOCAL_DETOUR_MAX_OFFSET_RATIO = 0.22;
	const LOCAL_DETOUR_MIN_INTERVAL = 0.5;
	const LOCAL_DETOUR_CORNER_GUARD_MIN = 2;
	const ENABLE_RUNTIME_DIAGNOSTICS = false;
	const ENABLE_PAD_EDGE_DIAGNOSTICS = true;
	const COPPER_REGION_REBUILD_TIMEOUT_MS = 60000;
	const FILL_MODE_SOLID = 0;
	const REGION_RULE_NO_FILLS = 6;
	const REGION_RULE_NO_POURS = 7;
	const REGION_RULE_FOLLOW_REGION_RULE = 9;
	const SINGLE_TARGET_SEGMENTS = 12;
	const DEFAULT_CONFIG = {
		generationType: 'fill',
		targetLayer: 1,
		expansion: DEFAULT_PAD_BBOX_EXPANSION,
		padBboxExpansion: DEFAULT_PAD_BBOX_EXPANSION,
		enableChamfer: false,
		chamferType: 'straight',
		chamferWidth: DEFAULT_CHAMFER_WIDTH,
		pour: {
			preserveSilos: false,
			manufacturingOptimization: true,
			pourFillMethod: 'solid',
		},
	};

	const namespace = global.AutoCopperPour = global.AutoCopperPour || {};
	namespace.constants = {
		PLUGIN_TAG,
		PCB_DOCUMENT_TYPE,
		SAFE_COPPER_WIDTH,
		POUR_LINE_WIDTH,
		MULTI_LAYER_ID,
		DEFAULT_PAD_BBOX_EXPANSION,
		DEFAULT_CHAMFER_WIDTH,
		CONFIG_KEY,
		SHOULD_USE_DYNAMIC_SHAPE,
		OBSTACLE_SEARCH_MARGIN,
		EDGE_BLOCK_FORWARD_SEARCH_MARGIN,
		OBSTACLE_LATERAL_MARGIN,
		TRACE_CAP_SEGMENTS,
		COPPER_NODE_CONTOUR_SEGMENTS,
		ROUND_RECT_CORNER_SEGMENTS,
		MIN_TRACE_CLIPPED_POLYGON_AREA,
		MIN_AVOIDANCE_NECK_WIDTH,
		EDGE_BLOCK_FORWARD_GAP,
		EDGE_BLOCK_CORNER_DOMINANCE_RATIO,
		EDGE_BLOCK_CORNER_GAP_BIAS,
		TRACE_NECK_REPAIR_MAX_PASSES,
		TRACE_NECK_TRACE_EDGE_TOLERANCE,
		TRACE_NECK_REPAIR_INNER_OVERLAP,
		MAX_DETOUR_LENGTH_RATIO,
		MAX_DETOUR_OFFSET_RATIO,
		MIN_DETOUR_CORNER_ANGLE,
		SHORT_BRIDGE_FALLBACK_GAP,
		SHORT_BRIDGE_DETOUR_OFFSET_RATIO,
		SHORT_BRIDGE_SPIKE_CORNER_ANGLE,
		LOCAL_DETOUR_MAX_OFFSET_RATIO,
		LOCAL_DETOUR_MIN_INTERVAL,
		LOCAL_DETOUR_CORNER_GUARD_MIN,
		ENABLE_RUNTIME_DIAGNOSTICS,
		ENABLE_PAD_EDGE_DIAGNOSTICS,
		COPPER_REGION_REBUILD_TIMEOUT_MS,
		FILL_MODE_SOLID,
		REGION_RULE_NO_FILLS,
		REGION_RULE_NO_POURS,
		REGION_RULE_FOLLOW_REGION_RULE,
		SINGLE_TARGET_SEGMENTS,
		DEFAULT_CONFIG,
	};
})(namespace);
